const router = require("express").Router();
const PDFDocument = require("pdfkit");
const pool = require("../db");
const { authenticate } = require("../middleware/auth");

router.get("/:id/pdf", authenticate, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT r.*, u.username AS requester, u.full_name AS requester_name, h.full_name AS hod_name
       FROM access_requests r
       LEFT JOIN users u ON r.created_by = u.id
       LEFT JOIN users h ON r.approved_by = h.id
       WHERE r.id = $1`,
      [req.params.id]
    );
    const req_data = rows[0];
    if (!req_data) return res.status(404).json({ error: "Not found" });
    if (req.user.role !== "e1" && req_data.created_by !== req.user.id)
      return res.status(403).json({ error: "Forbidden" });

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="access-request-${req_data.id}.pdf"`);
    doc.pipe(res);

    doc.fontSize(20).font("Helvetica-Bold").text("ISMS Helpdesk", { align: "center" });
    doc.fontSize(14).font("Helvetica").text("Access Request Form", { align: "center" });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#1E3A8A").lineWidth(2).stroke();
    doc.moveDown();

    const statusColor = req_data.status === "approved" ? "#22C55E" : req_data.status === "rejected" ? "#EF4444" : "#F59E0B";
    doc.fontSize(11).fillColor(statusColor).font("Helvetica-Bold").text(`Status: ${req_data.status.toUpperCase()}`, { align: "right" });
    doc.fillColor("#000000");
    doc.moveDown();

    const field = (label, value) => {
      doc.font("Helvetica-Bold").fontSize(10).text(label, { continued: true });
      doc.font("Helvetica").fontSize(10).text(`  ${value || "-"}`);
      doc.moveDown(0.4);
    };

    doc.font("Helvetica-Bold").fontSize(12).text("Request Details");
    doc.moveDown(0.5);
    field("Request ID:", `#${req_data.id}`);
    field("Employee Name:", req_data.employee_name);
    field("CPF No:", req_data.cpf_no);
    field("Submitted By:", req_data.requester_name || req_data.requester);
    field("Submitted At:", new Date(req_data.created_at).toLocaleString());
    doc.moveDown(0.5);

    doc.font("Helvetica-Bold").fontSize(12).text("Access Information");
    doc.moveDown(0.5);
    field("Text 1:", req_data.text1);
    field("Text 2:", req_data.text2);
    field("Remark:", req_data.remark);
    doc.moveDown(0.5);

    if (req_data.status !== "pending") {
      doc.font("Helvetica-Bold").fontSize(12).text("E1 Decision");
      doc.moveDown(0.5);
      field("Decision By:", req_data.hod_name || "E1 Approver");
      field("Decision At:", new Date(req_data.approved_at).toLocaleString());
      field("Remark:", req_data.hod_remark);
    }

    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#cccccc").lineWidth(1).stroke();
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor("#888888").text("Generated by ISMS Helpdesk - for official use only", { align: "center" });

    doc.end();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
